### ISSUE TITLE
Adding locales to the the load path affects I18n.available_locales

### ISSUE THREAD

**Issue by klobuczek** [codegram/date_validator#20]
The line below breaks the behavior of I18n.available_locales:

I18n.load_path += Dir[File.expand_path(File.join(File.dirname(**FILE**), '../locales', '*.yml')).to_s]

That is undesired behavior as some application dynamically figure out the available locales. Providing translations for DateValidator doesn't mean that the rest of the application is translated. None of the common gems are that intrusive and they provide at most english translation.
You can provide the locale files in the gem but do not load them all.

Thanks
Heinrich

**Comment by Uepsilon** [comment]
+1
