### ISSUE TITLE
URL out of date in repository description

### ISSUE THREAD

**Issue by harvath** [codegram/date_validator#72]
Something very small, maybe you guys already know about this.

> A simple, ORM agnostic, Ruby 1.9+ compatible date validator for Rails, based on ActiveModel. http://blog.codegram.com/2011/2/date-validation-with-rails-3

I suppose the correct URL as of now is http://thoughts.codegram.com/date-validation-with-rails-3 ?

**Comment by oriolgual** [comment]
Thanks!
