### ISSUE TITLE
Is this gem still maintained ?

### ISSUE THREAD

**Issue by kwent** [codegram/date_validator#81]
Hi,

I'm seeing lot of PR and not much activity. Is this gem still maintained?

Are you looking for a new maintainer? How can we help make this amazing gem improved?

Regards

**Comment by oriolgual** [comment]
Hi @kwent, thanks for opening the issue. Yes, it's still maintained although we've been quite busy and we didn't pay enough attention to it.

I can give you commit access if you want if you're interested in helping with it.

**Comment by alex-mohemian** [comment]
@oriolgual it would be awesome if you could take a look at the open pull requests
